server:
  port: 8088

test:
  name: xiaohong

spring:
  datasource:
    url: jdbc:mysql://rm-2zey080waq1749ox0uo.mysql.rds.aliyuncs.com/wiki?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    data-username: wiki
    data-password: Wiki123=
